// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VideoRentalMVC.Models;

#nullable disable

namespace VideoRentalMVC.Migrations
{
    [DbContext(typeof(VideoRentalDbContext))]
    [Migration("20260402131858_AddGiaVonPrecision")]
    partial class AddGiaVonPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VideoRentalMVC.Models.Bang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<string>("TenBang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaPhim");

                    b.ToTable("Bangs");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Khach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Khachs");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Phim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GiaVon")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NamSanXuat")
                        .HasColumnType("int");

                    b.Property<string>("NuocSanXuat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhimBoLe")
                        .HasColumnType("bit");

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Thue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaTraTienThue")
                        .HasColumnType("bit");

                    b.Property<int>("MaBang")
                        .HasColumnType("int");

                    b.Property<int>("MaKhach")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayThue")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MaBang");

                    b.HasIndex("MaKhach");

                    b.ToTable("Thues");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Bang", b =>
                {
                    b.HasOne("VideoRentalMVC.Models.Phim", "Phim")
                        .WithMany("Bangs")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phim");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Thue", b =>
                {
                    b.HasOne("VideoRentalMVC.Models.Bang", "MaBangNavigation")
                        .WithMany("Thues")
                        .HasForeignKey("MaBang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VideoRentalMVC.Models.Khach", "MaKhachNavigation")
                        .WithMany("Thues")
                        .HasForeignKey("MaKhach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaBangNavigation");

                    b.Navigation("MaKhachNavigation");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Bang", b =>
                {
                    b.Navigation("Thues");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Khach", b =>
                {
                    b.Navigation("Thues");
                });

            modelBuilder.Entity("VideoRentalMVC.Models.Phim", b =>
                {
                    b.Navigation("Bangs");
                });
#pragma warning restore 612, 618
        }
    }
}
